name: Publish Docker image

on:
  push:
    branches-ignore:
      - main # Exclude main branch from triggering
  pull_request:
    branches-ignore:
      - main # Exclude PRs targeting main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build the Docker image
        uses: docker/build-push-action@v6
        with:
          push: false # Do not push the image
          tags: user/app:latest # You can adjust this tag as needed
          cache-from: type=registry,ref=user/app:latest # Adjust this if necessary
          cache-to: type=inline
