name: Publish Docker image

on:
  push:
    branches-ignore:
      - main # Exclude main branch from triggering
  pull_request:
    branches-ignore:
      - main # Exclude PRs targeting main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build images
        run: docker compose build
